### PR TITLE
[Android] Fix javadoc build with JDK 1.8.

### PR DESCRIPTION
**Pull request by rakuco**
Fix build errors caused by commits 5505ef4 ("[Android] Refactor download
mode") and 1c6ecad ("[Android] Implement the method to set compositing
surface type for single XWalkView"):

```
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java:60: error: header used out of sequence: <H5>
 * <h5>Shared Mode</h5>
   ^
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkUpdater.java:172: error: header used out of sequence: <H5>
 * <h5>Shared Mode</h5>
   ^
../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkView.java:96: error: text not allowed in <ol> element
 *   </li></ul></li>
                    ^
```

### CODE REVIEW

**Comment by rakuco** [comment]
@lincsoon @xzhan96 @darktears

**Comment by lincsoon** [comment]
LGTM

**Comment by xzhan96** [comment]
LGTM
